trigger:
- main  # Change to your main branch name

pr:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello from Azure DevOps!
  displayName: 'Run a simple script'

- script: echo Checking out the code from GitHub
  displayName: 'Checkout GitHub code'
  env:
    REPOSITORY_NAME: 'https://github.com/robertwarnold/F23-Team02.git'
  workingDirectory: '$(Build.SourcesDirectory)'
- script: |
      git clone $(REPOSITORY_NAME) .

